name: Validate format & build

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  workflow_dispatch:

jobs:
  formatBackend:
    name: Validate format of backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Validate backend format
        run: cd backend && mvn spotless:check
  buildBackend:
    name: Build backend
    runs-on: ubuntu-latest
    needs: formatBackend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build backend
        run: cd backend && mvn package

  formatFrontend:
    name: Validate format of frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: cd frontend/app && npm install
      - name: Validate frontend linter
        run: cd frontend/app && npm run lint:validate
      - name: Validate frontend prettier
        run: cd frontend/app && npm run prettier:validate
  buildFrontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: formatFrontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build frontend
        run: cd frontend && mvn package

  buildAll:
    name: Build whole application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package