name: Validate format & build

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  workflow_dispatch:

jobs:
  formatBackend:
    name: Validate format of backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Validate backend format
        run: mvn spotless:check

  formatFrontend:
    name: Validate format of frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install frontend dependencies
        run: cd src/main/webui && npm install
      - name: Validate frontend linter
        run: cd src/main/webui && npm run lint:validate
      - name: Validate frontend prettier
        run: cd src/main/webui && npm run prettier:validate

  buildAll:
    name: Build whole application
    runs-on: ubuntu-latest
    needs:
      - formatBackend
      - formatFrontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package